package server

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// --- Example-Aware Generation E2E Tests (Task 22) ---

// buildExampleTestServer creates an httptest.Server from the example-test spec.
func buildExampleTestServer(t *testing.T) *httptest.Server {
	t.Helper()

	specBytes := loadSpecBytes(t, "e2e-example-test.yaml")

	handler, _, err := Build(context.Background(), specBytes, Config{Strict: true})
	require.NoError(t, err)

	return httptest.NewServer(handler)
}

func TestExampleE2E_FetchPet_UsesExampleValues(t *testing.T) {
	skipIfShort(t)

	srv := buildExampleTestServer(t)
	defer srv.Close()

	resp := doRequest(t, srv, http.MethodGet, "/pets/1")
	defer closeBody(t, resp)

	assert.Equal(t, http.StatusOK, resp.StatusCode)

	var pet map[string]any
	decodeJSON(t, resp, &pet)

	// Fields with examples should use the example values.
	assert.Equal(t, "Fido", pet["name"], "name should use example value")
	assert.Equal(t, "dog", pet["species"], "species should use example value")
	assert.InDelta(t, 101.0, pet["id"], 0.1, "id should use example value")
	assert.InDelta(t, 3.0, pet["age"], 0.1, "age should use example value")
	assert.InDelta(t, 4.5, pet["weight"], 0.1, "weight should use example value")
	assert.Equal(t, true, pet["vaccinated"], "vaccinated should use example value")
}

func TestExampleE2E_FetchPet_EnumBeatsExample(t *testing.T) {
	skipIfShort(t)

	srv := buildExampleTestServer(t)
	defer srv.Close()

	pet := getJSONObject(t, srv, "/pets/1")

	// "status" has both enum and example — enum should win.
	status, ok := pet["status"].(string)
	require.True(t, ok, "status should be a string")
	assert.Contains(t, []string{"available", "adopted", "pending"}, status,
		"status should be one of the enum values, not necessarily the example")
}

func TestExampleE2E_FetchPet_FieldsWithoutExamples(t *testing.T) {
	skipIfShort(t)

	srv := buildExampleTestServer(t)
	defer srv.Close()

	pet := getJSONObject(t, srv, "/pets/1")

	// "email" — no example but semantic mapper should produce an email-like value.
	email, ok := pet["email"].(string)
	require.True(t, ok, "email should be a string")
	assert.Contains(t, email, "@", "email field should use semantic mapper")

	// "tag" — no example, no semantic match, should still be a non-empty string.
	tag, ok := pet["tag"].(string)
	require.True(t, ok, "tag should be a string")
	assert.NotEmpty(t, tag, "tag should be generated by faker")
}

func TestExampleE2E_Determinism(t *testing.T) {
	skipIfShort(t)

	srv := buildExampleTestServer(t)
	defer srv.Close()

	pet1 := getJSONObject(t, srv, "/pets/1")
	pet2 := getJSONObject(t, srv, "/pets/1")

	assert.Equal(t, pet1, pet2, "same request should produce identical response")
}

func TestExampleE2E_ListPets_ExampleValuesInArray(t *testing.T) {
	skipIfShort(t)

	srv := buildExampleTestServer(t)
	defer srv.Close()

	resp := doRequest(t, srv, http.MethodGet, "/pets")
	defer closeBody(t, resp)

	assert.Equal(t, http.StatusOK, resp.StatusCode)

	var pets []map[string]any
	decodeJSON(t, resp, &pets)

	require.NotEmpty(t, pets, "should return at least one pet")

	// Each pet in the array should use example values for example-bearing fields.
	for i, pet := range pets {
		assert.Equal(t, "Fido", pet["name"], "pet[%d].name should use example", i)
		assert.Equal(t, "dog", pet["species"], "pet[%d].species should use example", i)
	}
}

func TestExampleE2E_StrictMode_PassesValidation(t *testing.T) {
	skipIfShort(t)

	// Server is built with Strict: true — responses that fail schema validation
	// would return 500 instead of 200.
	srv := buildExampleTestServer(t)
	defer srv.Close()

	resp := doRequest(t, srv, http.MethodGet, "/pets/1")
	defer closeBody(t, resp)

	assert.Equal(t, http.StatusOK, resp.StatusCode,
		"strict mode: response with example values should pass schema validation")
}
